# Generated by Django 4.0 on 2022-01-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macchinari',
            fields=[
                ('MacchinarioId', models.AutoField(primary_key=True, serialize=False)),
                ('MacchinarioName', models.CharField(max_length=500)),
                ('MacchinarioSn', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ReportId', models.AutoField(primary_key=True, serialize=False)),
                ('Seller', models.CharField(max_length=500)),
                ('EndUSer', models.CharField(max_length=500)),
                ('Macchinario', models.CharField(max_length=500)),
                ('MacchinarioSn', models.CharField(max_length=500)),
                ('DataIntervento', models.DateField()),
                ('Tecnico', models.CharField(max_length=500)),
                ('DataVendita', models.DateField()),
                ('ParteCat', models.CharField(max_length=500)),
            ],
        ),
    ]
