# Generated by Django 4.0.1 on 2022-01-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUsers',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('SellerId', models.AutoField(primary_key=True, serialize=False)),
                ('SellerName', models.CharField(max_length=500)),
            ],
        ),
    ]
