# Generated by Django 4.0.1 on 2022-01-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportManager', '0002_endusers_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='StatoRep',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
