# Generated by Django 4.0.1 on 2022-01-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportManager', '0003_report_statorep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componenti',
            fields=[
                ('CompId', models.AutoField(primary_key=True, serialize=False)),
                ('CompName', models.CharField(max_length=500)),
                ('Note', models.CharField(max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('TecnicoId', models.AutoField(primary_key=True, serialize=False)),
                ('TecnicoName', models.CharField(max_length=500)),
            ],
        ),
    ]
